Repository OpenSourceProgramming/INHA_OSAP_004_Froyo, pull requests merged in 2023-11, with the labels that each got.

#3 Chore: 프로젝트 세팅 (#2)
  .gitignore
  .vscode/settings.json
  .vscode/tasks.json
  main.cpp
Labels: Add, 승빈

#11 ADD: node.h 파일 추가 (#4)
  node.h
Labels: Add, 승빈

#17 REFACTOR: Node 클래스 구조 변경 (#15)
  node.h
  node_avl.h
Labels: Refactor, 승빈

#20 ADD: makefile 추가 (#19)
  .gitignore
  Makefile
  main.cc
  node.h
  set.h
  set_avl.cc
Labels: Add, 승빈

#25 feat: Insert 함수 구현 (#24)
  set_avl.cc
  set_avl.h
Labels: Feat, P1 / Priority High, 승빈

#32 feat : Maximum 기능 구현 (#30)
  set_avl.cc
Labels: Feat, 군량
