Repository OpenSourceProgramming/INHA_OSAP_004_Froyo, pull requests merged in 2023-12, with the labels that each got.

#34 feat: find 함수 구현 (#23)
  set_avl.cc
  set_avl.h
Labels: 이준 🦦, Feat, P1 / Priority High

#38 feat: 구글테스트 환경 구축, Insert 함수 return type 변경 (#33)
  CMakeLists.txt
  set.h
  set_avl.cc
  set_avl.h
  test_runner.cc
Labels: Test, Feat, 승빈

#37 Fix/Maximum 함수 버그 수정 #31
  set_avl.cc
Labels: Fix, 군량

#40 add: 라이선스 추가 (#39)
  LICENSE
Labels: Add, 승빈

#42 chore: 라이선스 주석 추가 (#41)
  CMakeLists.txt
  node.h
  node_avl.h
  set.h
  set_avl.cc
  set_avl.h
  test_runner.cc
Labels: Chore, 승빈

#36 feat: Minimum 함수 구현 및 세부사항 수정 (#26)
  set_avl.cc
Labels: Feat, 진우

#46 add: Advanced 기능 프로토타입 작성 (#43)
  set.h
  set_avl.cc
  set_avl.h
Labels: Add, P1 / Priority High, 승빈

#50 feat: Erase 기능 구현 (삭제하려고 하는 노드의 자식이 2개일 경우) (#47)
  node_avl.h
  set_avl.cc
  set_avl.h
Labels: Feat, 승빈

#56 set_avl.cc conflict 해결시도
  set_avl.cc
Labels: Fix, P1 / Priority High, 진우

#57 feat: Erase 기능 구현 (삭제하려고 하는 노드의 자식이 1개일 경우) #52
  set_avl.cc
Labels: Fix, Add, 진우

#62 add: 템플릿 추가 (#58), refactor: set_avl.cc header file화 (#60), add: main.cc에 기본 코드 작성 (#61)
  CMakeLists.txt
  main.cc
  node.h
  node_avl.h
  set.h
  set_avl.h
  set_avl.hpp
Labels: Refactor, Chore, Add, 승빈
